import { Card, CardTitle } from '../../components/ui/card';
import { SkeletonCard } from '../../../crm/components/ui/skeleton';
import { DollarSign, TrendingUp, CreditCard, Banknote, AlertCircle } from 'lucide-react';
import { useDriverStats, useDriverPayments } from '../../hooks/useDriverQuery';
export default function EarningsPage(){
  const { data: s, isLoading: sl, isError: se, refetch: sr } = useDriverStats() as any;
  const { data: p, isLoading: pl } = useDriverPayments() as any;
  if(sl || pl) return <div className="grid gap-4 sm:grid-cols-4">{Array.from({length:4}).map((_,i)=><SkeletonCard key={i} />)}</div>;
  if(se) return <Card className="text-center py-12"><AlertCircle className="h-10 w-10 mx-auto text-amber-500" /><p className="mt-2 font-medium">Could not load earnings</p><button onClick={()=>sr()} className="mt-3 rounded-full btn-brand-gradient px-5 py-2 text-sm text-white">Retry</button></Card>;
  const stats=s?.stats; const payments:any[]=(p?.payments??[]).slice(0,12);
  const cards = [
    { label:"Today's Earnings", value: stats?`${stats.totalEarnings.toFixed(2)}`:'—', icon:DollarSign },
    { label:"Weekly", value:'$342.00', icon:TrendingUp }, { label:"Monthly", value:'$1,240.00', icon:TrendingUp }, { label:"Lifetime", value: stats?`${stats.totalEarnings.toFixed(2)}`:'—', icon:Banknote },
  ];
  return (<div className="space-y-6"><h1 className="font-display text-2xl font-bold dark:text-white">Earnings</h1><div className="grid gap-4 sm:grid-cols-4">{cards.map(c=> <Card key={c.label}><div className="flex items-center gap-2"><c.icon className="h-4 w-4 text-brand-600" /><p className="text-xs uppercase tracking-widest text-muted">{c.label}</p></div><p className="font-display mt-2 text-2xl font-bold dark:text-white">{c.value}</p></Card>)}</div><div className="grid gap-6 lg:grid-cols-2"><Card><CardTitle>Cash vs Card • Tips • Bonuses</CardTitle><div className="mt-4 grid grid-cols-2 gap-3">{[ {k:'Cash',v:'$120.00',c:'bg-accent-50 dark:bg-white/5'}, {k:'Card',v:'$214.10',c:'bg-brand-50 dark:bg-brand-950 text-brand-700'}].map(x=> <div key={x.k} className={`rounded-2xl p-4 ${x.c}`}><p className="text-xs text-muted">{x.k}</p><p className="font-bold dark:text-white">{x.v}</p></div>)}</div></Card><Card><CardTitle>Commissions • Payouts</CardTitle>{payments.length ? <ul className="mt-3 space-y-2">{payments.map((x:any)=><li key={x._id} className="flex items-center justify-between rounded-2xl border border-accent-200 p-3 dark:border-white/5"><span className="text-sm capitalize">{x.method} • {x.status}</span><span className="font-semibold text-brand-700">${x.amount.toFixed(2)}</span></li>)}</ul> : <p className="mt-3 text-sm text-muted">No payouts yet — earnings appear after completed rides</p>}</Card></div><Card><CardTitle>Revenue Graph</CardTitle><div className="mt-4 flex h-28 items-end gap-1">{Array.from({length:14}).map((_,i)=><div key={i} className="flex-1 rounded-t-xl bg-brand-gradient" style={{height:`${16+Math.random()*70}px`}} />)}</div></Card></div>);
}