import { Card, CardTitle } from '../../components/ui/card';
import { SkeletonCard } from '../../../crm/components/ui/skeleton';
import { Wallet, CreditCard, TrendingUp, AlertCircle } from 'lucide-react';
import { useDriverPayments } from '../../hooks/useDriverQuery';

export default function WalletPage(){
  const { data, isLoading, isError, refetch } = useDriverPayments() as any;
  if(isLoading) return <div className="grid gap-4 sm:grid-cols-3">{Array.from({length:3}).map((_,i)=><SkeletonCard key={i} />)}</div>;
  if(isError) return <Card className="text-center py-12"><AlertCircle className="h-12 w-12 mx-auto text-amber-500" /><p className="mt-3 font-medium">Could not load wallet</p><button onClick={()=>refetch()} className="mt-3 rounded-full btn-brand-gradient px-5 py-2 text-sm text-white">Retry</button></Card>;
  const payments:any[] = data?.payments??[];
  const balance = payments.filter((p:any)=>p.status==='succeeded').reduce((s:number,p:any)=>s+p.amount,0);
  return (<div className="space-y-6"><h1 className="font-display text-2xl font-bold dark:text-white">Wallet</h1><div className="grid gap-4 sm:grid-cols-3"><Card><div className="flex items-center gap-2"><Wallet className="h-4 w-4 text-brand-600" /><p className="text-xs uppercase tracking-widest text-muted">Current Balance</p></div><p className="font-display mt-2 text-3xl font-bold dark:text-white">${balance.toFixed(2)}</p><button className="mt-3 min-h-11 rounded-full btn-brand-gradient px-5 py-2.5 text-sm font-semibold text-white">Withdraw</button></Card><Card><p className="text-xs uppercase tracking-widest text-muted">Available</p><p className="font-display mt-2 text-2xl font-bold dark:text-white">${(balance*0.9).toFixed(2)}</p><p className="text-xs text-muted">Pending ${(balance*0.1).toFixed(2)} • Last payout 2 days ago</p></Card><Card><p className="text-xs uppercase tracking-widest text-muted">Bank Account</p><p className="mt-2 text-sm font-medium dark:text-white">Chase **** 4821</p><p className="text-xs text-muted">Payment methods: Card, Wallet</p><span className="mt-2 inline-flex items-center gap-1 rounded-full bg-brand-50 px-2.5 py-1 text-xs text-brand-700"><CreditCard className="h-3 w-3" /> Verified</span></Card></div><Card><CardTitle>Transaction History</CardTitle>{payments.length ? <ul className="mt-4 space-y-2">{payments.slice(0,10).map((p:any)=><li key={p._id} className="flex items-center justify-between rounded-2xl border border-accent-200 p-3 dark:border-white/5"><span className="text-sm">{p.ride?.pickup?.address?.slice(0,30) || 'Ride'} • {p.status}</span><span className="font-semibold text-brand-700">+${p.amount.toFixed(2)}</span></li>)}</ul> : <div className="mt-6 text-center py-8"><TrendingUp className="h-12 w-12 mx-auto text-accent-300" /><p className="mt-2 text-sm text-muted">No transactions yet — complete a ride to see earnings</p></div>}</Card></div>);
}