import { Card, CardTitle } from '../../components/ui/card';
import { useState } from 'react';
import { Moon, Globe, MapPin, Lock, Shield } from 'lucide-react';
export default function SettingsPage(){
  const [dark,setDark]=useState(false);
  const [lang,setLang]=useState('English');
  return (<div className="max-w-2xl space-y-6"><h1 className="font-display text-2xl font-bold dark:text-white">Settings</h1><Card><CardTitle>Preferences</CardTitle><div className="mt-4 space-y-4">{[
    { icon:Moon, label:'Dark Mode', control: <label className="relative inline-flex cursor-pointer items-center"><input type="checkbox" checked={dark} onChange={e=>{setDark(e.target.checked); document.documentElement.classList.toggle('dark', e.target.checked);}} className="peer sr-only" /><div className="peer h-6 w-11 rounded-full bg-accent-200 peer-checked:bg-brand-600 after:absolute after:left-[2px] after:top-[2px] after:h-5 after:w-5 after:rounded-full after:bg-white after:transition-all peer-checked:after:translate-x-5" /></label> },
    { icon:Globe, label:'Language', control: <select value={lang} onChange={e=>setLang(e.target.value)} className="input-pill min-h-11 border border-accent-200 bg-white px-4 py-2 text-sm dark:border-white/10 dark:bg-transparent"><option>English</option><option>Español</option></select> },
    { icon:MapPin, label:'Location Sharing', control: <label className="relative inline-flex cursor-pointer items-center"><input type="checkbox" defaultChecked className="peer sr-only" /><div className="peer h-6 w-11 rounded-full bg-brand-600 peer-checked:bg-brand-600 after:translate-x-5 after:bg-white" /></label> },
  ].map(row=> <div key={row.label} className="flex items-center justify-between rounded-2xl border border-accent-200 p-4 dark:border-white/5"><div className="flex items-center gap-3"><row.icon className="h-5 w-5 text-brand-600" /><span className="font-medium dark:text-white">{row.label}</span></div>{row.control}</div>)}</div></Card><Card><CardTitle>Security & Privacy</CardTitle><div className="space-y-3 text-sm"><div className="flex items-center justify-between rounded-2xl bg-accent-50 p-4 dark:bg-white/5"><div className="flex items-center gap-2"><Lock className="h-4 w-4 text-brand-600" /><span className="dark:text-white">Two-Factor Auth</span></div><span className="rounded-full bg-green-50 px-2.5 py-1 text-xs font-medium text-green-700">Enabled</span></div><div className="flex items-center justify-between rounded-2xl bg-accent-50 p-4 dark:bg-white/5"><div className="flex items-center gap-2"><Shield className="h-4 w-4 text-brand-600" /><span className="dark:text-white">Privacy • Data sharing</span></div><span className="text-xs text-muted">Manage</span></div></div></Card></div>);
}